name: firstproject

on:
  push:
     branches: [Main]
     
jobs:
   testing:
     runs-on: ubuntu-latest

     steps:
       - name: Time Test
         run: echo "Hello Pankaj Shukla, Go Home 7:03PM"
